name:                xauth-native
version:             0.1.0.0
github:              "githubuser/xauth-native"
license:             BSD3
author:              "Ivan Yudin"
maintainer:          "yudinivan@yahoo.de"
copyright:           "2022 Ivan Yudin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/xauth-native#readme>

dependencies:
- base 
- bytestring
- attoparsec
- mtl  

ghc-options:
- -Weverything
- -Werror
- -Wno-missing-export-lists
- -Wno-missing-import-lists
- -Wno-type-defaults
- -Wno-safe
- -Wno-unsafe
- -Wno-unused-imports
- -Wno-unused-matches
- -Wno-implicit-prelude

library:
  source-dirs: lib 
